# Generated by Django 4.2.4 on 2023-08-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='surname',
            field=models.TextField(default='Diker'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.TextField(default='Burak'),
        ),
    ]
