# Generated by Django 4.2.4 on 2023-08-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_tool', '0003_remove_usermodel_is_admin_remove_usermodel_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
