# Generated by Django 4.2.4 on 2023-08-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_tool', '0004_usermodel_password_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OutputValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OutputPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('output_unit', models.CharField(max_length=50)),
                ('output_values', models.ManyToManyField(to='calc_tool.outputvalue')),
            ],
        ),
        migrations.CreateModel(
            name='InputPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('input_values', models.ManyToManyField(to='calc_tool.inputvalue')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_list_json', models.TextField()),
                ('input_pages', models.ManyToManyField(to='calc_tool.inputpage')),
                ('output_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_tool.outputpage')),
            ],
        ),
    ]
