# Generated by Django 4.2.4 on 2023-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_tool', '0007_imagemodel_alter_outputpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputpage',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
