# Generated by Django 4.2.4 on 2023-09-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_tool', '0008_alter_outputpage_image_delete_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('index', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='outputpage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_tool.imagemodel'),
        ),
    ]
