# Generated by Django 4.2.4 on 2023-09-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_tool', '0009_imagemodel_alter_outputpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputpage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_tool.imagemodel'),
        ),
    ]
